### PR TITLE
Fix #991: Local and TaskRunLoop

### LINKED ISSUE #991: NullPointerException in CanBindLocals / Local.isolate?
Shit, I think we have a problem in the latest release:

```
java.lang.NullPointerException
	at monix.execution.misc.CanBindLocals.isolate(CanBindLocals.scala:54)
	at monix.execution.misc.CanBindLocals.isolate$(CanBindLocals.scala:53)
	at monix.execution.misc.CanIsolateInstancesLevel0$SynchronousInstance$.isolate(CanBindLocals.scala:111)
	at monix.execution.misc.Local$.isolate(Local.scala:86)
	at monix.eval.internal.TaskRunLoop$.startFull(TaskRunLoop.scala:143)
	at monix.eval.internal.TaskRunLoop$.$anonfun$restartAsync$2(TaskRunLoop.scala:217)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at monix.execution.misc.CanIsolateInstancesLevel0$SynchronousInstance$.bindContext(CanBindLocals.scala:115)
	at monix.execution.misc.Local$.bind(Local.scala:94)
	at monix.eval.internal.TaskRunLoop$.$anonfun$restartAsync$1(TaskRunLoop.scala:215)
	at monix.execution.internal.InterceptableRunnable$Wrapped.run(InterceptableRunnable.scala:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

### PR DESCRIPTION
**Pull request by alexandru**
See #991 for details.

### CODE REVIEW

**Comment by alexandru** [comment]
Released hash version for testing: `3.0.0-RC4-99273a4`

File: monix-eval/shared/src/main/scala/monix/eval/internal/TaskRunLoop.scala [hunk 1]
```diff
@@ -212,9 +212,17 @@ private[eval] object TaskRunLoop {
         context.frameRef.reset()
 
         // Transporting the current context if localContextPropagation == true.
-        Local.bind(savedLocals) {
+        var prevLocals: Local.Context = null
+        if (savedLocals != null) {
```
Comment (Avasil) [inline monix-eval/shared/src/main/scala/monix/eval/internal/TaskRunLoop.scala]: Is it needed if there is already a null check in `Local.bind`? Or is it just to inline?

Comment (alexandru) [reply monix-eval/shared/src/main/scala/monix/eval/internal/TaskRunLoop.scala]: I'm doing this for inlining, since `Local.bind` is no longer a macro and I don't want to have the penalty of that call in case locals are not disabled.
