### PR TITLE
Make Task propagate RejectedExecutionException

### LINKED ISSUE #651: Task should deal with RejectedExecutionException
In issue #594 we are described a situation in which thread-pools that can throw
[RejectedExecutionException](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/RejectedExecutionException.html) are used.

But if that happens in methods such as `executeAsync`, `executeOn`, `shift`, or `asyncBoundary`, we aren't catching and streaming the exception and the tasks will become non-terminating.

In these functions dealing with `Scheduler`, we need to catch exceptions that are triggered by `Scheduler#execute` and stream it as an error via the provided callback. It's safe doing so because execute is supposed to be async, so if `execute` throws then we can be sure that the callback wasn't called.

### PR DESCRIPTION
**Pull request by oleg-py**
Fix #651, #594.

Getting `RejectedExecutionException` requires a manually created Executor with a `BlockingQueue` of finite size. It cannot be done with monix Scheduler factory methods nor with Executors ones.

Scala.js has `REE` too: https://github.com/scala-js/scala-js/blob/master/javalib/src/main/scala/java/util/concurrent/Throwables.scala#L22, so no platform-specific code is required.

### CODE REVIEW

**Comment by oleg-py** [comment]
It's a bit complicated, because it only works for shift-based methods and executeOn. It's not enough if you try to use a bounded queue-based executor as your main one.

**Comment by oleg-py** [comment]
@alexandru seems to not run correctly on Travis.

I can create a fake ExecutorService that always throws RejectedExecutionException, tho it might make the test less... legitimate.

**Comment by alexandru** [comment]
@oleg-py I think creating a fake `ExecutionContext` is totally fine. We just need to catch and handle that particular exception, no complicated logic there.

File: monix-eval/shared/src/main/scala/monix/eval/Task.scala [hunk 1]
```diff
@@ -2174,12 +2176,17 @@ object Task extends TaskInstancesLevel1 {
...
+      try {
+        ec2.execute(new Runnable {
+          def run(): Unit = {
+            context.frameRef.reset()
+            cb.onSuccess(())
+          }
+        })
+      } catch {
+        case ex: RejectedExecutionException =>
+          cb.onError(ex)
```
Comment (alexandru) [inline monix-eval/shared/src/main/scala/monix/eval/Task.scala]: Works, but use `cb.asyncOnError(ex)` as it's safer — I make it a habit of doing that in `Async` states in order to ensure stack safety, as you never know how it ends up being used. It's not needed for `onSuccess` here because you have `ec2.execute` first.

**Comment by alexandru** [comment]
This PR diverged from master unfortunately.

**Comment by pettyjamesm** [comment]
I should say, since I reported the issue that in our case we choose to stop making the database ThreadPool implement Scheduler and just use Task.create with a surrounding try / catch to handle this case.

The next surprise was discovering that the callback would start running the subsequent logic on the database ThreadPool threads, but I know that master already changed the behavior to shift back to the default scheduler. Any idea when a new RC will be released? I'd like to make sure that our tracing implementation (using Local) and workaround still work after all the internal changes I've seen merged lately.
