### PR TITLE
Fix local isolate

### LINKED ISSUE #966: Local.isolate sometimes doesn't isolate properly in between async boundaries
See the comment in the snippet:

```scala
import monix.execution.misc.Local
import monix.execution.schedulers.TracingScheduler

import scala.concurrent.duration._
import scala.concurrent.{Await, ExecutionContext, Future}

object Main extends App {
  implicit val s = TracingScheduler(ExecutionContext.global)

  val local = Local(0)

//  Sometimes fails with:
//  scala-execution-context-global-306-0
//  scala-execution-context-global-286-50
//  scala-execution-context-global-286-isolate1-50
//  scala-execution-context-global-306-isolate2-50
//  scala-execution-context-global-286-100
  val f1 = for {
    _ <- Future{
      println(Thread.currentThread.getName + s"-${local()}")
      assert(local() == 0)
      local := 50
    }
    _ <- Future{
      println(Thread.currentThread.getName + s"-${local()}")
      assert(local() == 50)
    }
    _ <- Local.isolate{
      println(Thread.currentThread.getName + s"-isolate1-${local()}")
      Future  {
          println(Thread.currentThread.getName + s"-isolate2-${local()}")
          assert(local() == 50)
          local := 100
      }
    }
    _ <- Future{
      println(Thread.currentThread.getName + s"-${local()}")
      assert(local() == 50)
    }
  } yield ()

  Await.result(f1, Duration.Inf)
}
```
cc @alexandru @oleg-py

### PR DESCRIPTION
**Pull request by Avasil**
Fixes #966 

Not finished but might be easier to discuss

### CODE REVIEW

File: monix-eval/shared/src/main/scala/monix/eval/Task.scala [hunk 1]
```diff
@@ -580,9 +580,11 @@ sealed abstract class Task[+A] extends Serializable with TaskDeprecated.BinCompa
...
   def runToFutureOpt(implicit s: Scheduler, opts: Options): CancelableFuture[A] = {
     val opts2 = opts.withSchedulerFeatures
-    Local.bindCurrentIf(opts2.localContextPropagation) {
-      TaskRunLoop.startFuture(this, s, opts2)
-    }
+    Local
+      .bindCurrentAsyncIf(opts2.localContextPropagation) {
+        TaskRunLoop.startFuture(this, s, opts2)
+      }
+      .asInstanceOf[CancelableFuture[A]]
```
Comment (Avasil) [inline monix-eval/shared/src/main/scala/monix/eval/Task.scala]: I hope there is a way to do it without it

File: monix-eval/shared/src/test/scala/monix/eval/TaskLocalSuite.scala [hunk 2]
```diff
@@ -268,4 +268,88 @@ object TaskLocalSuite extends SimpleTestSuite {
...
+        Task.evalAsync(local := 100).flatMap(_ => Task.raiseError(DummyException("boom")))
+      }.attempt
+      v <- Task.evalAsync(local())
+      _ <- Task.now(assertEquals(v, 50))
+    } yield ()
+
+    test.runToFutureOpt
+  }
+
+  testAsync("TaskLocal.isolate should properly isolate during async boundaries on cancelation") {
```
Comment (Avasil) [inline monix-eval/shared/src/test/scala/monix/eval/TaskLocalSuite.scala]: This test fails currently

File: monix-eval/shared/src/test/scala/monix/eval/TaskLocalSuite.scala [hunk 3]
```diff
@@ -268,4 +268,88 @@ object TaskLocalSuite extends SimpleTestSuite {
...
+        Task.evalAsync(local := 100).start.flatMap(_.cancel)
+      }
+      v <- Task.evalAsync(local())
+      _ <- Task.now(assertEquals(v, 50))
+    } yield ()
+
+    test.runToFutureOpt
+  }
+
+  testAsync("Running task isolates locals") {
```
Comment (Avasil) [inline monix-eval/shared/src/test/scala/monix/eval/TaskLocalSuite.scala]: This one fails too even for `runToFuture`, not sure why

File: monix-execution/shared/src/main/scala/monix/execution/misc/Local.scala [hunk 4]
```diff
@@ -78,12 +95,18 @@ object Local {
...
+  /** If `b` evaluates to `true`, execute a synchronous block of code using a current
     * state of `Local.Context` and restore the current state when complete.
     */
   def bindCurrentIf[R](b: => Boolean)(f: => R): R =
     macro Macros.localLetCurrentIf
 
+  /** If `b` evaluates to `true`, execute an asynchronous block of code using a current
+    * state of `Local.Context` and restore the current state when complete.
+    */
+  def bindCurrentAsyncIf[R](b: => Boolean)(f: => Future[R]): Future[R] =
```
Comment (Avasil) [inline monix-execution/shared/src/main/scala/monix/execution/misc/Local.scala]: couldn't just overload because of `(b: => Boolean)` I suppose

File: monix-execution/shared/src/test/scala/monix/execution/misc/LocalSuite.scala [hunk 5]
```diff
@@ -73,8 +75,10 @@ object LocalSuite extends SimpleTestSuite {
     local2 := 100
 
     val f = Local.isolate {
-      local1 := 100
-      Future(local1.get + local2.get)
+      Future {
```
Comment (Avasil) [inline monix-execution/shared/src/test/scala/monix/execution/misc/LocalSuite.scala]: with current changes
```scala
Local.isolate {
  local1 := 100
  Future (...)
}
```
currently goes for `Future` variant but doesn't isolate properly :( unless we stick modification inside
```

File: monix-execution/shared/src/test/scala/monix/execution/misc/LocalSuite.scala [hunk 6]
```diff
@@ -73,8 +75,10 @@ object LocalSuite extends SimpleTestSuite {
...
+        local1 := 100
+        local1.get + local2.get
```
Comment (Avasil) [inline monix-execution/shared/src/test/scala/monix/execution/misc/LocalSuite.scala]: it returns updated `local1` (100) + `local2` (999) from below unless we do something use `local2` here

Comment (Avasil) [reply monix-execution/shared/src/test/scala/monix/execution/misc/LocalSuite.scala]: fixed both cases

File: monix-execution/shared/src/test/scala/monix/execution/misc/LocalSuite.scala (hunk 5 above)
Comment (Avasil) [reply monix-execution/shared/src/test/scala/monix/execution/misc/LocalSuite.scala]: fixed both cases

File: monix-eval/shared/src/test/scala/monix/eval/TaskLocalSuite.scala (hunk 3 above)
Comment (Avasil) [reply monix-eval/shared/src/test/scala/monix/eval/TaskLocalSuite.scala]: Small update:
```scala
val f = p.future

f.map(_ => {
    assert(local() == 0, s"received ${local()} != expected 0 in $method")
})
```

fails if `f` is not isolated

File: monix-eval/shared/src/test/scala/monix/eval/TaskLocalSuite.scala (hunk 2 above)
Comment (Avasil) [reply monix-eval/shared/src/test/scala/monix/eval/TaskLocalSuite.scala]: Fixed by not restoring locals in `TaskStart`

File: monix-eval/shared/src/test/scala/monix/eval/TaskLocalSuite.scala (hunk 3 above)
Comment (Avasil) [reply monix-eval/shared/src/test/scala/monix/eval/TaskLocalSuite.scala]: @oleg-py Is it a bug or feature? :D

File: monix-execution/shared/src/main/scala/monix/execution/misc/Local.scala (hunk 4 above)
Comment (oleg-py) [reply monix-execution/shared/src/main/scala/monix/execution/misc/Local.scala]: There's actually no point in having `b` being by-name here. It will always be strictly evaluated.

File: monix-execution/shared/src/main/scala/monix/execution/misc/Local.scala [hunk 7]
```diff
@@ -60,12 +62,34 @@ object Local {
...
+    * changes outside.
+    */
+  def isolate[R](f: => Future[R]): Future[R] = {
+    // TODO: rewrite as macro
+    val prev = Local.getContext()
+    val current = Local.getContext().mkIsolated
+    Local.setContext(current)
+
+    try {
+      f.transform(result => {
```
Comment (oleg-py) [inline monix-execution/shared/src/main/scala/monix/execution/misc/Local.scala]: Can't you use `Try[A] => Try[B]` overload here to have just one lambda?

File: monix-execution/shared/src/main/scala/monix/execution/misc/Local.scala [hunk 8]
```diff
@@ -294,8 +324,24 @@ final class Local[A](default: () => A) {
   def bind[R](value: A)(f: => R): R = {
     val parent = Local.getContext()
     Local.setContext(parent.bind(key, Some(value)))
-    try f
-    finally Local.setContext(parent)
+
+    f match {
+      case future: Future[_] =>
+        future
+          .transform(result => {
```
Comment (oleg-py) [inline monix-execution/shared/src/main/scala/monix/execution/misc/Local.scala]: Same as above

File: monix-execution/shared/src/main/scala/monix/execution/misc/Local.scala [hunk 9]
```diff
@@ -304,13 +350,28 @@ final class Local[A](default: () => A) {
   def bindClear[R](f: => R): R = {
     val parent = Local.getContext()
     Local.setContext(parent.bind(key, None))
-    try f
-    finally Local.setContext(parent)
+
+    f match {
+      case future: Future[_] =>
+        future
+          .transform(result => {
```
Comment (oleg-py) [inline monix-execution/shared/src/main/scala/monix/execution/misc/Local.scala]: Same

File: monix-eval/jvm/src/test/scala/monix/eval/TaskLocalJVMSuite.scala [hunk 10]
```diff
@@ -174,4 +177,87 @@ object TaskLocalJVMSuite extends SimpleTestSuite {
...
+    def runAssertion(run: Task[Unit] => Any, method: String): Future[Unit] = {
+      val p = Promise[Unit]
+      val local = Local(0)
+      val task = Task.evalAsync(local := 50).guarantee(Task(p.success(())).void)
+
+      run(task)
+
+      // Future could still carry isolated local
+      // because it was created inside isolated block
+      val f = Local.isolate(p.future)
```
Comment (oleg-py) [inline monix-eval/jvm/src/test/scala/monix/eval/TaskLocalJVMSuite.scala]: Does `isolate` actually do anything here?

File: monix-eval/shared/src/main/scala/monix/eval/Task.scala (hunk 1 above)
Comment (oleg-py) [reply monix-eval/shared/src/main/scala/monix/eval/Task.scala]: I don't think there is. But `bind..If` is somewhat of internal method, we can make a version for `CancelableFuture` and make it private.

File: monix-execution/shared/src/main/scala/monix/execution/misc/Local.scala (hunk 4 above)
Comment (Avasil) [reply monix-execution/shared/src/main/scala/monix/execution/misc/Local.scala]: Good point, I'll change it although it is still ambigious reference to overloeaded definition if we prefer overload.

File: monix-execution/shared/src/main/scala/monix/execution/misc/Local.scala (hunk 7 above)
Comment (Avasil) [reply monix-execution/shared/src/main/scala/monix/execution/misc/Local.scala]: I think it's not available in `2.11`

File: monix-eval/jvm/src/test/scala/monix/eval/TaskLocalJVMSuite.scala (hunk 10 above)
Comment (Avasil) [reply monix-eval/jvm/src/test/scala/monix/eval/TaskLocalJVMSuite.scala]: Yes, otherwise it will carry the state of `Local` from the place of `Promise` completion. Not sure if it's a bug or a feature

File: monix-eval/shared/src/main/scala/monix/eval/Task.scala (hunk 1 above)
Comment (Avasil) [reply monix-eval/shared/src/main/scala/monix/eval/Task.scala]: Hmm, maybe it could make sense to make `bindCurrentIf` private as well? It's basically `if p isolate(x) else x` so if anyone needs it - he can add it easily

File: monix-execution/shared/src/main/scala/monix/execution/misc/Local.scala (hunk 7 above)
Comment (oleg-py) [reply monix-execution/shared/src/main/scala/monix/execution/misc/Local.scala]: Oh, right

File: monix-eval/shared/src/test/scala/monix/eval/TaskLocalSuite.scala (hunk 3 above)
Comment (oleg-py) [reply monix-eval/shared/src/test/scala/monix/eval/TaskLocalSuite.scala]: I'd say it's a quirk, I don't think it can be solved.

File: monix-eval/shared/src/main/scala/monix/eval/Task.scala (hunk 1 above)
Comment (oleg-py) [reply monix-eval/shared/src/main/scala/monix/eval/Task.scala]: Yes, that what I was thinking of :)

File: monix-execution/shared/src/main/scala/monix/execution/misc/Local.scala (hunk 7 above)
Comment (Avasil) [reply monix-execution/shared/src/main/scala/monix/execution/misc/Local.scala]: I guess we can always create `Future.transform` in version specific modules to optimize it for `2.12` and `2.13` but not sure if it matters right now

File: monix-eval/shared/src/test/scala/monix/eval/TaskLocalSuite.scala (hunk 3 above)
Comment (Avasil) [reply monix-eval/shared/src/test/scala/monix/eval/TaskLocalSuite.scala]: Yeah, I tried but failed miserably :D I guess we can live with it. I'm not sure if it's even a use case we should support

File: monix-execution/shared/src/main/scala/monix/execution/misc/Local.scala (hunk 7 above)
Comment (Avasil) [reply monix-execution/shared/src/main/scala/monix/execution/misc/Local.scala]: Actually, I think we have `transform` in `FutureUtils`, I'll try it

**Comment by Avasil** [comment]
@oleg-py Thank you for the review, I updated PR:
- Removed duplicated test
- used `FutureUtils.transform` 
- changed `bindCurrentif` to `private[monix]`

File: monix-execution/shared/src/main/scala/monix/execution/misc/Local.scala [hunk 11]
```diff
@@ -60,12 +64,31 @@ object Local {
...
+  /** Execute a synchronous block of code without propagating any `Local.Context`
     * changes outside.
     */
   def isolate[R](f: => R): R =
     macro Macros.isolate
 
+  /** Execute an asynchronous block of code without propagating any `Local.Context`
+    * changes outside.
+    */
+  def isolate[R](f: => Future[R]): Future[R] = {
```
Comment (alexandru) [inline monix-execution/shared/src/main/scala/monix/execution/misc/Local.scala]: I am concerned about this overload.

The old one is a macro, this one is not. Also I know that the JVM cannot differentiate between `R` and `Future[R]`, especially here because we have a by-name parameter which translates into a `Function0`.

I'm thinking that we should no longer use a macro here. I'm not convinced that we gain anything by it. Macros are fine for internal functions, were we don't want the overhead of that closure, but for user code it just makes things complicated.

So I'm thinking that maybe we should introduce a type class, because why not:

```scala
trait CanIsolate[R] {
  def isolate(f: => R): R
}

//...

object Local {
  def isolate[R : CanIsolate](f: => R): R =
    CanIsolate[R].isolate(f)
}
```

Given that what we had was a macro, I don't think this would violate any binary compatibility.

Not sure about how this should behave in the context of `Task` though. Or if it's a good idea. Just a suggestion.

File: monix-execution/shared/src/main/scala/monix/execution/misc/Local.scala [hunk 12]
```diff
@@ -294,8 +338,21 @@ final class Local[A](default: () => A) {
   def bind[R](value: A)(f: => R): R = {
     val parent = Local.getContext()
     Local.setContext(parent.bind(key, Some(value)))
-    try f
-    finally Local.setContext(parent)
+
+    f match {
```
Comment (alexandru) [inline monix-execution/shared/src/main/scala/monix/execution/misc/Local.scala]: Note that this does not have the semantic of the original code — `f` is a by-name parameter and you're evaluating it twice.

Also the first time you're evaluating `f`, it isn't in the context of a try/catch statement. This means that if `f` throws an error, you're not restoring the context.

Also this pattern matching here is not future proof. It isn't idiomatic Scala so to speak. If we really need to discriminate between data types like this, then we should use implicits.

File: monix-execution/shared/src/main/scala/monix/execution/misc/Local.scala (hunk 11 above)
Comment (Avasil) [reply monix-execution/shared/src/main/scala/monix/execution/misc/Local.scala]: I agree with macro, I meant to rewrite it to macro later but only because of consistency. I think we could safely remove it (and possibly reintroduce if it turns out it's needed). I know Oleg kept it for similar reasons

> So I'm thinking that maybe we should introduce a type class, because why not:
> ...

Hmm, I think it could work, we could have an instance for `Future` and then a lower priority instance for everything else. I can't tell if it's an improvement or not, to me it seems similar to having overload

> Not sure about how this should behave in the context of Task though. Or if it's a good idea. Just a suggestion.

`Task` has a different function for isolate on `TaskLocal` which does `bracket`. We could add an instance for normal `Local` in `Task` object I guess if it will be higher priority than default one for `Local` (not sure, needs to check)

WDYT @oleg-py ?

File: monix-execution/shared/src/main/scala/monix/execution/misc/Local.scala (hunk 12 above)
Comment (Avasil) [reply monix-execution/shared/src/main/scala/monix/execution/misc/Local.scala]: > Note that this does not have the semantic of the original code — f is a by-name parameter and you're evaluating it twice.
> Also the first time you're evaluating f, it isn't in the context of a try/catch statement. This means that if f throws an error, you're not restoring the context.

Right, I will fix it

> Also this pattern matching here is not future proof. It isn't idiomatic Scala so to speak. If we really need to discriminate between data types like this, then we should use implicits.

What do you mean by "future proof" ?

File: monix-execution/shared/src/main/scala/monix/execution/misc/Local.scala (hunk 11 above)
Comment (oleg-py) [reply monix-execution/shared/src/main/scala/monix/execution/misc/Local.scala]: I have no preference here. Typeclasses will work as well as `asInstanceOf`, really, unless you push it to properly isolate `Option[Future[Option[Future[A]]]]`. You'll also have to make sure it works properly with our `CancelableFuture`, that it doesn't fall back to lower priority instance.

> maybe we should introduce a type class, because why not

🤣
